version: '3'
services:
  node:
    build: .
    container_name: "A1b_bot_node"
    restart: always
    depends_on:
      - db
    environment:
      PGHOST: "db"
      PGUSER: "${PGUSER}"
      PGPASSWORD: "${PGPASSWORD}"
      PGDATABASE: "${PGDATABASE}"
  db:
    image: postgres
    container_name: "A1b_bot_db"
    restart: always
    environment:
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_DB: "${PGDATABASE}"
    ports:
      - '${PGPORT}:5432'
    volumes:
      - ./sql:/sql
      - ./db:/var/lib/postgresql/data
      - ./sql/start.sql:/docker-entrypoint-initdb.d/start.sql
