version: '3'
services:
  node:
    restart: always
    build: .
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    ports:
      - '${PGPORT}:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local